export const NAKSHATRA_OPTIONS = [
  { value: "Ashwini", label: "Ashwini (அஸ்வினி)" },
  { value: "Bharani", label: "Bharani (பரணி)" },
  { value: "Krittika", label: "Krittika (கிருத்திகை)" },
  { value: "Rohini", label: "Rohini (ரோஹிணி)" },
  { value: "Mrigashira", label: "Mrigashira (மிருகசீரிடம்)" },
  { value: "Ardra", label: "Ardra (திருவாதிரை)" },
  { value: "Punarvasu", label: "Punarvasu (புனர்பூசம்)" },
  { value: "Pushya", label: "Pushya (பூசம்)" },
  { value: "Ashlesha", label: "Ashlesha (ஆயில்யம்)" },
  { value: "Magha", label: "Magha (மகம்)" },
  { value: "Purva Phalguni", label: "Purva Phalguni (பூரம்)" },
  { value: "Uttara Phalguni", label: "Uttara Phalguni (உத்திரம்)" },
  { value: "Hasta", label: "Hasta (ஹஸ்தம்)" },
  { value: "Chitra", label: "Chitra (சித்திரை)" },
  { value: "Swati", label: "Swati (சுவாதி)" },
  { value: "Vishakha", label: "Vishakha (விசாகம்)" },
  { value: "Anuradha", label: "Anuradha (அனுஷம்)" },
  { value: "Jyeshtha", label: "Jyeshtha (கேட்டை)" },
  { value: "Mula", label: "Mula (மூலம்)" },
  { value: "Purva Ashadha", label: "Purva Ashadha (பூராடம்)" },
  { value: "Uttara Ashadha", label: "Uttara Ashadha (உத்திராடம்)" },
  { value: "Shravana", label: "Shravana (திருவோணம்)" },
  { value: "Dhanishta", label: "Dhanishta (அவிட்டம்)" },
  { value: "Shatabhisha", label: "Shatabhisha (சதயம்)" },
  { value: "Purva Bhadrapada", label: "Purva Bhadrapada (பூரட்டாதி)" },
  { value: "Uttara Bhadrapada", label: "Uttara Bhadrapada (உத்திரட்டாதி)" },
  { value: "Revati", label: "Revati (ரேவதி)" },
] as const;

export const RASI_OPTIONS = [
  { value: "Mesha", label: "Mesha (மேஷம்) - Aries" },
  { value: "Rishabha", label: "Rishabha (ரிஷபம்) - Taurus" },
  { value: "Mithuna", label: "Mithuna (மிதுனம்) - Gemini" },
  { value: "Kataka", label: "Kataka (கடகம்) - Cancer" },
  { value: "Simha", label: "Simha (சிம்மம்) - Leo" },
  { value: "Kanya", label: "Kanya (கன்னி) - Virgo" },
  { value: "Tula", label: "Tula (துலாம்) - Libra" },
  { value: "Vrischika", label: "Vrischika (விருச்சிகம்) - Scorpio" },
  { value: "Dhanus", label: "Dhanus (தனுசு) - Sagittarius" },
  { value: "Makara", label: "Makara (மகரம்) - Capricorn" },
  { value: "Kumbha", label: "Kumbha (கும்பம்) - Aquarius" },
  { value: "Meena", label: "Meena (மீனம்) - Pisces" },
] as const;
