export const MUSLIM_SECTS = [
  "Sunni",
  "Hanafi",
  "Maliki",
  "Shafi'i",
  "Hanbali",
  "Athari",
  "Ash'ari",
  "Maturidi",
  "Salafi",
  "Ahl al-Hadith",
  "Deobandi",
  "Barelvi",
  "Ahl-i Hadith (South Asia)",
  "Jamaat-e-Islami",
  "Tablighi Jamaat",
  "Shia",
  "Twelver (Ithna Ashari)",
  "Ismaili",
  "Nizari Ismaili",
  "Musta'li Ismaili",
  "Dawoodi Bohra",
  "Sulaymani Bohra",
  "Alavi Bohra",
  "Zaidi",
  "Jarudiyya",
  "Sulaymaniyya",
  "Batriyya",
  "Kaysanite",
  "Mukhtariyya",
  "Waqifiyya",
  "Fathiyya",
  "Ghulat",
  "Alawite (Nusayri)",
  "Druze",
  "Alevi",
  "Ibadi",
  "Azariqa",
  "Najdat",
  "Sufriyya",
  "Ibadi (Historical Branch)",
  "Haruriyya",
  "Kharijite",
  "Mu'tazila",
  "Qadariyya",
  "Jabriyya",
  "Murji'ah",
  "Jahmiyya",
  "Karramiyya",
  "Mushabbihah",
  "Mujassimah",
  "Batiniyya",
  "Hurufiyya",
  "Nuqtawi",
  "Ahmadiyya",
  "Quranist",
  "Mahdavia",
  "Zikri",
  "Yazdani",
  "Nation of Islam",
  "Moorish Science Temple",
  "Five Percent Nation",
  "Sufi",
  "Qadiriyya",
  "Naqshbandiyya",
  "Chishtiyya",
  "Shadhiliyya",
  "Rifa'iyya",
  "Suhrawardiyya",
  "Mevlevi",
  "Bektashi",
  "Tijaniyya",
  "Sanusiyya",
  "Khalwatiyya"
];

export const MUSLIM_COMMUNITIES = [
  "Syed",
  "Sheikh",
  "Ansari",
  "Qureshi",
  "Pathan",
  "Mughal",
  "Malik",
  "Memon",
  "Khoja",
  "Dawoodi Bohra",
  "Suleimani Bohra",
  "Alavi Bohra",
  "Rowther",
  "Labbai",
  "Marakkayar",
  "Kayalar",
  "Mappila",
  "Beary",
  "Cutchi Memon",
  "Konkani Muslim",
  "Meo",
  "Gaddi Muslim",
  "Fakir",
  "Julaha",
  "Mansoori",
  "Saifi",
  "Siddiqui",
  "Farooqi",
  "Usmani",
  "Chishti"
];
