export const NAKSHATRA_OPTIONS = [
  { value: "Ashwini", label: "Ashwini" },
  { value: "Bharani", label: "Bharani" },
  { value: "Krittika", label: "Krittika" },
  { value: "Rohini", label: "Rohini" },
  { value: "Mrigashira", label: "Mrigashira" },
  { value: "Ardra", label: "Ardra" },
  { value: "Punarvasu", label: "Punarvasu" },
  { value: "Pushya", label: "Pushya" },
  { value: "Ashlesha", label: "Ashlesha" },
  { value: "Magha", label: "Magha" },
  { value: "Purva Phalguni", label: "Purva Phalguni" },
  { value: "Uttara Phalguni", label: "Uttara Phalguni" },
  { value: "Hasta", label: "Hasta" },
  { value: "Chitra", label: "Chitra" },
  { value: "Swati", label: "Swati" },
  { value: "Vishakha", label: "Vishakha" },
  { value: "Anuradha", label: "Anuradha" },
  { value: "Jyeshtha", label: "Jyeshtha" },
  { value: "Mula", label: "Mula" },
  { value: "Purva Ashadha", label: "Purva Ashadha" },
  { value: "Uttara Ashadha", label: "Uttara Ashadha" },
  { value: "Shravana", label: "Shravana" },
  { value: "Dhanishta", label: "Dhanishta" },
  { value: "Shatabhisha", label: "Shatabhisha" },
  { value: "Purva Bhadrapada", label: "Purva Bhadrapada" },
  { value: "Uttara Bhadrapada", label: "Uttara Bhadrapada" },
  { value: "Revati", label: "Revati" },
] as const;

export const RASI_OPTIONS = [
  { value: "Mesha", label: "Mesha - Aries" },
  { value: "Rishabha", label: "Rishabha - Taurus" },
  { value: "Mithuna", label: "Mithuna - Gemini" },
  { value: "Kataka", label: "Kataka - Cancer" },
  { value: "Simha", label: "Simha - Leo" },
  { value: "Kanya", label: "Kanya - Virgo" },
  { value: "Tula", label: "Tula - Libra" },
  { value: "Vrischika", label: "Vrischika - Scorpio" },
  { value: "Dhanus", label: "Dhanus - Sagittarius" },
  { value: "Makara", label: "Makara - Capricorn" },
  { value: "Kumbha", label: "Kumbha - Aquarius" },
  { value: "Meena", label: "Meena - Pisces" },
] as const;
